### ISSUE TITLE
Day 1 returns 35 instead of 300

### ISSUE THREAD

**Issue by kkirsche** [kkirsche/AdventOfCode#1]
@abates — I see in https://github.com/abates/AdventOfCode/tree/master/2016/01 you return 300 for the input.txt file which I have, yet mine returns 35. From what I see, it's doing the same thing, if north, @y += spaces, if south @y -= spaces, east @x += spaces, west @x -= spaces. Yet when I take the distance, which is the absolute value of @x + @y, I end up with 35. Not sure I know what I'm missing here, do you have any time to look at [this to see what I'm doing wrong?](https://github.com/kkirsche/AdventOfCode/tree/master/lib/adventOfCode/days/01)?

**EDIT**: Updated with new URL for the gem. A gem was just overall a better organization pattern

**Comment by kkirsche** [comment]
Potentially worth noting, the tests:

* Following R2, L3 leaves you 2 blocks East and 3 blocks North, or 5 blocks away.
* R2, R2, R2 leaves you 2 blocks due South of your starting position, which is 2 blocks away.
* R5, L5, R5, R3 leaves you 12 blocks away.

All return the correct values. This can be seen in `bin/tests`

**Comment by abates** [comment]
Hi Kevin,

I'll take a look this morning!

Andrew

**Comment by abates** [comment]
So my solution ends in a completely different position (164,-136) than
yours does (-4,31).  In both cases, our solutions compute the correct
manhattan distance, so the issue isn't in the distance calculation but in
the algorithm that moves the position with the input.

Is 35 the correct answer for your input?

Andrew

**Comment by abates** [comment]
I think I found your bug.  Remarkably I had an almost identical error in my
original go code.  I caught that error last week so it kind of jumped out
at me when looking at your code.

https://github.com/kkirsche/AdventOfCode/compare/master...abates:master

Andrew

**Comment by kkirsche** [comment]
Wow, that was the exact issue. So to make sure I understand the change(s):

```ruby
@spaces = direction[1,2].to_i
```

changes to

```ruby
@spaces = direction[1..-1].to_i
```

because we want to make sure that we capture any long distance. 1,2 just collects those two fields rather than an event that may be 3+ digits. Geez, what a "simple" bug, that hid. Thanks for looking at that @abates — that was the issue and with that change, allowed me to now get the right answer.

I really appreciate you taking the time to review that!
